repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c "cd tudu && cargo fmt -- --check"
        language: system
        pass_filenames: false
        types: [rust]

      - id: cargo-clippy
        name: cargo clippy
        entry: bash -c "cd tudu && cargo clippy -- -D warnings"
        language: system
        pass_filenames: false
        types: [rust]

      - id: cargo-test
        name: cargo test
        entry: bash -c "cd tudu && cargo test"
        language: system
        pass_filenames: false
