# .tudu.yaml example
scan:
  # ignore specific paths; alternative to `.tuduignore`
  ignore:
    - target/
    - node_modules/
  # include specific paths
  include:
    - "**/*"
  match_case_insensitive: false
mode: validate  # validate | sync
providers:
  notion:
    type: "notion"
    # token: should come from env var NOTION_TOKEN
    database_id: "25dc4188fa0e806c9dd1f4e7327751c5"
output:
  format: standard  # standard | json
  verbose: false 
